### ISSUE TITLE
runtime errors (linux)

### ISSUE THREAD

**Issue by berger-n** [buda-base/tibetan-ocr-app#1]
hi! 
I've managed to run the app under linux/debian but had to go through some issues:
- first when I run `pip install -r requirements.txt` it said:
```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information. 
```
  something I had already experienced, the solution is to run `python3 -m venv path/to/venv` then `path/to/venv/bin/pip install -r requirements.txt` (here's the list of the packages versions [requirements.log](https://github.com/user-attachments/files/18274395/requirements.log), and I'm using `Python 3.11.2`)

- maybe it should be noted somewhere that you have to quit and run the app again after setting the models directory? otherwise they won't show up in the selector

- when I load an image I get this trace:
```
File "/BDRC/tibetan-ocr-app/BDRC/Widgets/Layout.py", line 1085, in add_image_widget
    image_widget = ImageListWidget(
                   ^^^^^^^^^^^^^^^^
TypeError: ImageListWidget.__init__() missing 1 required positional argument: 'resource_dir
```
  adding `resource_dir=os.getcwd()` at the given line seemed to fix it

- then when I run the OCR I get this error:
```
File "/BDRC/tibetan-ocr-app/BDRC/MVVM/view.py", line 301, in run_ocr
    status, result = self.ocr_pipeline.run_ocr(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'run_ocr'
```
  a quick look at the code made me fix this by commenting this line in `AppView.__init__`:
```
  if ocr_model is not None:
      self.ocr_pipeline = OCRPipeline(
          self.platform,
          ocr_model.config,
          line_config)
  else:
      self.ocr_pipeline = None
  
  #self.ocr_pipeline = None

  self.show()
```

- then again
```
File "/BDRC/tibetan-ocr-app/BDRC/Widgets/Layout.py", line 1391, in update_text
    text_widget = TextWidget(ocr_line, self.qfont)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TextWidget.__init__() missing 1 required positional argument: 'resource_dir'
```
  same fix as above worked

- then it worked! what an amazing piece of work, congratulations!
- using [this text](https://iiif.bdrc.io/bdr:I1NLM8424_001::I1NLM8424_0010021.jpg/full/max/0/default.jpg) found in the [Recent Acquisitions on BUDA](https://library-dev.bdrc.io/show/bdr:W1NLM8424?s=%2Fshow%2Fbdr%3AMW1NLM8424%3Fs%3D%252Ftradition%252Fbo%252F%253FsortBy%25253DfirstScanSyncDate_desc%26#open-viewer) I tried to copy/paste the first two lines and translate with Claude, it said *I apologize, but I cannot accurately translate this Tibetan text. It appears to be Classical Tibetan containing Buddhist mantras (with syllables like ཨོཾ/Om and ཧཱུཾ/Hum), but a proper translation would require expertise in Classical Tibetan.*
- then with Dharmamitra I got the following:  

  *With "dam rdzur pa bdud rtsi 'bru po sgrogs pa'i g.yogs mdo," and "tsho saḥ hūṃ," all the local deities and so forth, and all the sentient beings of the six realms and the intermediate state, are offered the nectar of the samaya substances.*

  *With "o āḥ haṃ," the offerings are presented to the six families, purifying obscurations and transforming into the mother of space.*

  BTW when I added the third line of the ocr in Dharmamitra it loops displaying *oṃ āḥ hūṃ* 
  (and [the link to this result](https://dharmamitra.org/?input_encoding=auto&view=search&target_lang=english&model=default&input_sentence=%0A%E0%BD%96%E0%BC%8D%E0%BC%88%E0%BD%91%E0%BC%8B%E0%BD%98%E0%BC%8B%E0%BD%A2%E0%BE%AB%E0%BD%B4%E0%BD%A2%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%96%E0%BD%91%E0%BD%B4%E0%BD%91%E0%BC%8B%E0%BD%A2%E0%BE%A9%E0%BD%B2%E0%BD%93%E0%BC%8B%E0%BD%A0%E0%BD%96%E0%BD%B4%E0%BC%8B%E0%BD%94%E0%BD%BC%E0%BC%8D%E0%BD%A6%E0%BE%92%E0%BD%BC%E0%BD%A2%E0%BD%A6%E0%BC%8B%E0%BD%82%E0%BE%B2%E0%BD%BC%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%98%E0%BD%91%E0%BD%91%E0%BD%BC%E0%BC%8E%E0%BD%A0%E0%BD%99%E0%BD%BC%E0%BC%8B%E0%BD%A6%E0%BD%B1%E0%BD%BF%E0%BD%A7%E0%BD%B1%E0%BD%B4%E0%BD%BE%E0%BD%82%E0%BD%B2%E0%BD%A6%E0%BC%8B%E0%BD%82%E0%BD%9E%E0%BD%B2%E0%BC%8B%E0%BD%96%E0%BD%91%E0%BD%82%E0%BC%8B%E0%BD%A6%E0%BD%BC%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%91%E0%BD%84%E0%BC%8B%E0%BC%8D%E0%BD%A2%E0%BD%B2%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%91%E0%BE%B2%E0%BD%B4%E0%BD%82%E0%BC%8B%E0%BD%96%E0%BD%A2%E0%BC%8B%E0%BD%91%E0%BD%BC%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A6%E0%BD%BA%E0%BD%98%E0%BD%A6%E0%BC%8B%E0%BD%85%E0%BD%93%E0%BC%8B%0A%E0%BD%90%E0%BD%98%E0%BD%A6%E0%BC%8B%E0%BD%85%E0%BD%91%E0%BC%8B%E0%BD%A3%E0%BC%8D%E0%BD%91%E0%BD%98%E0%BC%8B%E0%BD%A2%E0%BE%AB%E0%BD%A6%E0%BC%8B%E0%BD%96%E0%BD%A2%E0%BE%A1%E0%BD%B4%E0%BD%91%E0%BC%8B%2B%E0%BD%A8%E0%BD%B2%E0%BD%A0%E0%BD%96%E0%BE%B2%E0%BD%B4%E0%BD%A3%E0%BC%8B%E0%BD%A3%E0%BD%BC%E0%BC%8B%E0%BD%A6%E0%BE%92%E0%BE%B2%E0%BD%BC%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%82%E0%BE%B1%E0%BD%B4%E0%BD%A2%E0%BC%8B%E0%BD%99%E0%BD%B2%E0%BD%82%E0%BC%8D%E0%BD%A8%E0%BD%BC%E0%BC%8B%E0%BD%A8%E0%BD%B1%E0%BD%BF%E0%BD%A7%E0%BD%BE%E0%BC%8B%E0%BD%82%E0%BD%B2%E0%BD%A6%E0%BC%8B%E0%BD%A2%E0%BD%B2%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%87%E0%BD%B4%E0%BD%82%E0%BC%8B%E0%BD%94%E0%BD%A2%E0%BC%8B%E0%BD%A2%E0%BD%BC%E0%BC%8B%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A3%E0%BC%8B%E0%BD%95%E0%BD%B4%E0%BD%A3%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BC%8B%E0%BD%A6%E0%BE%92%E0%BE%B2%E0%BD%B2%E0%BD%96%E0%BC%8B%E0%BD%82%E0%BD%85%E0%BD%B2%E0%BD%A6%E0%BC%8B%E0%BD%96%E0%BE%B1%E0%BD%A2%E0%BC%8B%E0%BD%A2%E0%BD%A6%E0%BC%8B%E0%BD%98%E0%BD%81%E0%BD%A0%E0%BC%8B%E0%BD%A6%E0%BE%90%E0%BE%B1%E0%BD%BA%E0%BD%91%E0%BC%8B%E0%BD%98%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A6%E0%BE%B2%E0%BD%B4%E0%BD%A2%E0%BC%8B%E0%BD%82%E0%BE%B1%E0%BD%B4%E0%BD%A2%E0%BC%8B%E0%BD%96%E0%BD%A2%E0%BC%8B%0A%E0%BD%8F%E0%BD%A3%E0%BE%80%E0%BD%93%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BD%98%E0%BC%8B%E0%BD%A3%E0%BC%8D%E0%BD%A2%E0%BD%BA%E0%BC%8B%E0%BD%A2%E0%BC%8B%E0%BD%A6%E0%BC%8B%E0%BD%98%E0%BD%A2%E0%BE%A1%E0%BE%B1%E0%BD%A3%E0%BC%8B%E0%BD%A0%E0%BD%96%E0%BD%B4%E0%BD%A3%E0%BC%8B%E0%BD%96%E0%BC%8B%E0%BD%A2%E0%BD%B2%E0%BC%8D%E0%BD%A8%E0%BD%BC%E0%BD%BE%E0%BC%8B%E0%BD%96%E0%BD%9B%E0%BE%B2%E0%BC%8B%E0%BD%94%E0%BD%B1%E0%BD%B4%E0%BC%8B%E0%BD%98%E0%BD%B2%E0%BC%8B%E0%BD%98%E0%BD%B1%E0%BD%BF%E0%BD%A7%E0%BD%B1%E0%BD%B2%E0%BD%BE%E0%BC%8D%E0%BD%91%E0%BD%94%E0%BD%A2%E0%BC%8B%E0%BD%86%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%82%E0%BD%A6%E0%BD%BA%E0%BD%A2%E0%BC%8B%E0%BD%82%E0%BE%B1%E0%BD%B2%E0%BC%8B%E0%BD%A6%E0%BC%8B%E0%BD%82%E0%BD%9E%E0%BD%B2%E0%BC%8D%E0%BD%A8%E0%BD%BC%E0%BC%8B%E0%BD%96%E0%BD%9B%E0%BE%B2%E0%BC%8B%E0%BD%A2%E0%BD%B2%E0%BC%8B%E0%BD%8E%E0%BD%B2%E0%BC%8B%E0%BD%A6%E0%BD%B1%E0%BD%BF%E0%BD%A7%E0%BE%B2%E0%BD%B1%E0%BD%B2%E0%BD%BE%E0%BC%8D%E0%BD%95%E0%BE%B1%E0%BD%B2%E0%BC%8B%E0%BD%A3%E0%BE%95%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%A2%E0%BD%B2%E0%BC%8B%E0%BD%81%E0%BD%BC%E0%BD%A2%E0%BC%8B%E0%BD%A1%E0%BD%B4%E0%BD%82%E0%BC%8B%E0%BD%82%E0%BD%B2%E0%BC%8B%E0%BD%A6%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BE%90%E0%BD%BC%E0%BD%A2%E0%BC%8B%E0%BD%96%E0%BD%A0%E0%BD%B2%E0%BC%8B) return 502)
  but this one should be posted in their own issues instead! @eroux do you know if this is possible? 
  
  ![simplescreenrecorder-2024-12-30_12 48 54 mkv](https://github.com/user-attachments/assets/655ac416-c254-41a7-bc89-06ed7f35b956)

- then more of this error, preventing the zoom +/- from working [edit: I meant zooming the text output]:
```
File "/BDRC/tibetan-ocr-app/BDRC/Widgets/Layout.py", line 1332, in zoom_in
    text_widget = TextWidget(ocr_line, self.qfont)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TextWidget.__init__() missing 1 required positional argument: 'resource_dir'
```

- what about a button to select/copy all the lines at once? :sweat_smile:

**Comment by eroux** [comment]
Oh wow, that's a lot of different issues :) thanks for the report though it's very useful!

Here's some answers:

> first when I run pip install -r requirements.txt it said

yes, that's not really specific to the app though, it's just a feature of the Python management under recent versions of Debian

> maybe it should be noted somewhere that you have to quit and run the app again after setting the models directory? otherwise they won't show up in the selector

oh really? interesting, I added a note in https://github.com/buda-base/tibetan-ocr-app/commit/2c3fd8153a808d9ac20def544ea99dc977fa8660

> TypeError: ImageListWidget.__init__() missing 1 required positional argument: 'resource_dir

right: https://github.com/buda-base/tibetan-ocr-app/commit/8e6b42d3b8c5d456e49fad2df5c8c801ec7b90df

> AttributeError: 'NoneType' object has no attribute 'run_ocr'

https://github.com/buda-base/tibetan-ocr-app/commit/0f0d246ce5c8316a92ad072282ff8d7e85159ed9

> TypeError: TextWidget.__init__() missing 1 required positional argument: 'resource_dir'

https://github.com/buda-base/tibetan-ocr-app/commit/335f40ab1c1ca6ae105bfae39401f80c6a1a147c

> then it worked! what an amazing piece of work, congratulations!

Thanks!!

> but this one should be posted in their own issues instead! @eroux do you know if this is possible?

I think they're always happy to get this kind of feedback yes, their website says to send them feedback by email (the address is on the website)

> what about a button to select/copy all the lines at once?

Good point! I thought there was one but there isn't currently... Let's open another issue for this

Thanks!

**Comment by berger-n** [comment]
thanks! now everything works just out of the box, there's just this warning in the console:

```
kenlm python bindings are not installed. Most likely you want to install it using: pip install 
https://github.com/kpu/kenlm/archive/master.zip
```
